name: Rust

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get -y install podman
        cargo install cross
        cross build --release --target x86_64-pc-windows-gnu

    - name: distribute
      run: |
        mkdir rust_and_dust_collector_snapshot-windows
        mv target/x86_64-pc-windows-gnu/release/rust_and_dust_collector.exe rust_and_dust_collector_snapshot-windows
        cp -r resources rust_and_dust_collector_snapshot-windows
        cp credits.txt license.txt rust_and_dust_collector_snapshot-windows
        zip -r rust_and_dust_collector_snapshot-windows.zip rust_and_dust_collector_snapshot-windows

    - name: Update binaries of development snapshot
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rust_and_dust_collector_snapshot-windows.zip
        asset_name: rust_and_dust_collector_snapshot-windows.zip
        tag: dev_snapshot
        overwrite: true

    - name: List files
      run: |
        ls -la

