name: Rust

on:
  workflow_dispatch:
    
  # push:
    # branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt install libasound2-dev
        cargo build --release
    - name: Run tests
      run: cargo test --verbose

    - name: distribute
      run: |
        mkdir rust_and_dust_collector_snapshot-ubuntu
        mv target/debug/rust_and_dust_collector rust_and_dust_collector_snapshot-ubuntu
        cp -r resources rust_and_dust_collector_snapshot-ubuntu
        cp credits.txt license.txt rust_and_dust_collector_snapshot-ubuntu
        zip -r rust_and_dust_collector_snapshot-ubuntu.zip rust_and_dust_collector_snapshot-ubuntu
        
    - name: Update binaries of development snapshot
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rust_and_dust_collector_snapshot-ubuntu.zip
        asset_name: rust_and_dust_collector_snapshot-ubuntu.zip
        tag: dev_snapshot
        overwrite: true

    - name: List files
      run: |
        ls -la

