name: Rust

on:
  workflow_dispatch:
    
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get install alsa-base alsa-utils
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: distribute
      run: |
        mv target/debug/rust_and_dust_collector .
        zip -r rust_and_dust_collector.zip resources rust_and_dust_collector

    - name: Update binaries of development snapshot
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rust_and_dust_collector.zip
        asset_name: rust_and_dust_collector_snapshot.zip
        tag: dev_snapshot
        overwrite: true
